# Generated by Django 2.1.2 on 2018-10-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vuforia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', models.CharField(max_length=100, unique=True)),
                ('secret_key', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'vuforia',
            },
        ),
    ]
